<a href="https://colab.research.google.com/github/kuikml/Data_Science/blob/master/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

Norma wektora, dlugosc wektora w R2

v = |x, y|

||v|| = √( x2 + y2 )

In [ ]:
v1 = np.array([0,4])
v1 = /

array([0, 4])

In [ ]:
np.linalg.norm(v1)

4.0

Norma Euklidesowa w Rn

In [ ]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

Odleglosc dwoch punktow na plaszczyznie

In [4]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

Odleglosc dwoch punktow w przestrzeni Rn

In [5]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

5.0990195135927845

Multiplying matrices

Aby móc pomnożyć dwie macierze liczba kolumn w lewej 
macierzy musi zgadzać się z liczbą wierszy w prawej macierzy

In [8]:
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])
print(x)
print(y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [9]:
z = np.dot(x, y)
z

array([[ 2],
       [-6]])

In [13]:
x = np.array([[2, -1, 3], [3, 1, 0]])
y = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])
z = np.dot(x, y)
z

array([[13,  9, -4],
       [ 6,  2, -1]])

Determinant of the matrix

In [17]:
a = np.array([[2, 4] , [-1, 3]])
round(np.linalg.det(a))

10.0

Matrix trace

In [18]:
a = np.array([[2, 4] , [-1, 3]])
np.trace(a)

5

Identity matrix

In [19]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Inverse matrix

Macierz musi być kwadratowa, macierz A posiada macierz odwrotną gdy macierz B || AB = BA = I

In [24]:
a = np.array([[2, 4] , [-1, 3]])
b = np.linalg.inv(a)
b

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [26]:
np.linalg.inv(b)

array([[ 2.,  4.],
       [-1.,  3.]])

In [29]:
np.set_printoptions(precision=4, suppress=True)

np.dot(a, b)

array([[ 1., -0.],
       [ 0.,  1.]])

In [30]:
np.dot(b, a)

array([[ 1., -0.],
       [ 0.,  1.]])

Transposed matrix

Zamiana wierszy na kolumny i kolumny na wiersze

In [31]:
np.transpose(a)

array([[ 2, -1],
       [ 4,  3]])

In [32]:
a.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązwywanie układów równań 
Sloving systems of equations

Jeśli macierz ukladu A jest macierzą kwadratową to oznaczalność układu jest równoważne jej odwracalności:
AX = B    
A-1AX = A-1B    
X = A-1B
Gdzie A-1 to macierz odwrotna

In [47]:
a = np.array([[2, 4],[1, -1]])
a1 = np.linalg.inv(a)
a1

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [46]:
b = np.array([[10], [-1]])
np.dot(a1, b)

array([[1.],
       [2.]])