<a href="https://colab.research.google.com/github/kuikml/Data_Science/blob/master/Nauka/Numpy_wprowadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array


In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1, 2.3, 4.5, 11.2, 13])
print(x)

[ 1.   2.3  4.5 11.2 13. ]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1,3,6],[2,7,8]])
x

array([[1, 3, 6],
       [2, 7, 8]])

In [ ]:
x.shape

(2, 3)

In [ ]:
x.ndim

In [ ]:
x = np.array([[1,3,4,6],[1,6,8,9]])
x
print(x)

[[1 3 4 6]
 [1 6 8 9]]


In [ ]:
x.shape

(2, 4)

In [ ]:
x = np.array([[1,6,4],[7,8,1],[5,9,4]])
print(x)

[[1 6 4]
 [7 8 1]
 [5 9 4]]


3D Array

In [ ]:
x = np.array(
    [[[4,6,8],
      [1,3,5]],
     [[7,4,1],
      [2,6,8]],
     [[1,0,9],
      [6,7,8]],
     [[4,7,9],
      [9,5,4]]]
)
print(x)

[[[4 6 8]
  [1 3 5]]

 [[7 4 1]
  [2 6 8]]

 [[1 0 9]
  [6 7 8]]

 [[4 7 9]
  [9 5 4]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(4, 2, 3)

Data Types

In [ ]:
a = np.array([1,3,5])
a.dtype

dtype('int64')

In [ ]:
a = np.array([1.7,3.6,5.0])
a.dtype

dtype('float64')

In [ ]:
a = np.array([1,3,5], dtype='float')
a.dtype

dtype('float64')

In [ ]:
a = np.array([1,3,5], dtype='complex')
a.dtype
a

array([1.+0.j, 3.+0.j, 5.+0.j])

In [ ]:
a = np.array([1.7,3.6,5.0], dtype='int')
a.dtype
a

array([1, 3, 5])

In [ ]:
a = np.array([True, False, True])
a.dtype

dtype('bool')

In [ ]:
a = np.array([23, 130, 240], dtype=np.int8)
a.dtype

dtype('int8')

In [ ]:
a = np.array([23, 130, 240], dtype=np.uint8)
a.dtype

dtype('uint8')

Creating Arrays

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(2,5,3), dtype='int')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
np.ones(shape=(4,4), dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full(shape=(5,5), fill_value=4, dtype='int')

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=1, stop=3000, step=249, dtype='int')

array([   1,  250,  499,  748,  997, 1246, 1495, 1744, 1993, 2242, 2491,
       2740, 2989])

In [ ]:
np.arange(start=100, stop=10, step=-10, dtype='int')

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.03, dtype='float')

array([0.  , 0.03, 0.06, 0.09, 0.12, 0.15, 0.18, 0.21, 0.24, 0.27, 0.3 ,
       0.33, 0.36, 0.39, 0.42, 0.45, 0.48, 0.51, 0.54, 0.57, 0.6 , 0.63,
       0.66, 0.69, 0.72, 0.75, 0.78, 0.81, 0.84, 0.87, 0.9 , 0.93, 0.96,
       0.99])

In [ ]:
np.linspace(start=0, stop=1, num=12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [ ]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape((-1,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A * 2

array([6, 2, 8, 4])

In [ ]:
abs(B)

array([3, 1, 3, 2])

In [ ]:
X = np.array([[3,4],[2,3]])
Y = np.array([[2,1],[5,3]])
print(X, '\n')
print(Y)

[[3 4]
 [2 3]] 

[[2 1]
 [5 3]]


In [ ]:
X * Y

array([[ 4, 12],
       [ 1,  9]])

In [ ]:
np.dot(X, Y)

array([[26, 15],
       [19, 11]])

In [ ]:
X.dot(Y)

array([[26, 15],
       [19, 11]])

In [ ]:
Y.dot(X)

array([[ 8, 11],
       [21, 29]])

In [ ]:
X @ Y

array([[26, 15],
       [19, 11]])

Generating Pseudo Random Numbers

In [8]:
np.random.seed(0)

In [9]:
np.random.randn()

1.764052345967664

In [10]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [13]:
np.random.randn(10, 4)

array([[ 0.53924919, -0.67433266,  0.03183056, -0.63584608],
       [ 0.67643329,  0.57659082, -0.20829876,  0.39600671],
       [-1.09306151, -1.49125759,  0.4393917 ,  0.1666735 ],
       [ 0.63503144,  2.38314477,  0.94447949, -0.91282223],
       [ 1.11701629, -1.31590741, -0.4615846 , -0.06824161],
       [ 1.71334272, -0.74475482, -0.82643854, -0.09845252],
       [-0.66347829,  1.12663592, -1.07993151, -1.14746865],
       [-0.43782004, -0.49803245,  1.92953205,  0.94942081],
       [ 0.08755124, -1.22543552,  0.84436298, -1.00021535],
       [-1.5447711 ,  1.18802979,  0.31694261,  0.92085882]])

In [14]:
np.random.rand()

0.27354203481563577

In [15]:
np.random.rand(10, 2)

array([[0.79804683, 0.18563594],
       [0.95279166, 0.68748828],
       [0.21550768, 0.94737059],
       [0.73085581, 0.25394164],
       [0.21331198, 0.51820071],
       [0.02566272, 0.20747008],
       [0.42468547, 0.37416998],
       [0.46357542, 0.27762871],
       [0.58678435, 0.86385561],
       [0.11753186, 0.51737911]])

In [18]:
np.random.randint(low=10, high=100, size=8)

array([61, 28, 44, 61, 40, 63, 68, 53])

In [21]:
np.random.choice(['python', 'php', 'julia'])

'julia'

In [23]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.random.shuffle(data)
data

array([8, 5, 7, 6, 2, 0, 1, 4, 3, 9])

Functions

In [28]:
np.exp(2)

7.38905609893065

In [27]:
np.sqrt(9)

3.0

In [32]:
np.all([2,3,1])

True

In [35]:
np.any([0,0,2,0,0])

True

In [39]:
A = np.random.rand(5)
A

array([0.01323686, 0.34723352, 0.14814086, 0.98182939, 0.47837031])

In [40]:
np.argmax(A)

3

In [41]:
A[np.argmax(A)]

0.9818293898182532

In [42]:
A[np.argmin(A)]

0.01323685775889949

In [43]:
np.argsort(A)

array([0, 2, 1, 4, 3])

In [44]:
np.max(A)

0.9818293898182532

In [45]:
np.min(A)

0.01323685775889949

In [46]:
np.mean(A)

0.3937621866995051

In [47]:
np.median(A)

0.34723351793221957

In [48]:
np.std(A)

0.3347464258383992

Indexing / Cutting

In [71]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [104]:
#A[index], A[start:stop], A[:stop], A[start:], A[::step], A[[index, index]]

In [70]:
A[::2]

array([[ 0,  6,  7,  8,  4],
       [10,  1,  2,  3, 14]])

In [54]:
A[[2,6]]

array([2, 6])

In [72]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
A[1]

array([5, 6, 7, 8, 9])

In [58]:
A[:,2]

array([ 2,  7, 12, 17])

In [60]:
A[1,2]

7

In [62]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [87]:
np.random.shuffle(A[1:3,1:4])
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
A[1,2] = np.ones(1)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  1,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Itterations over arrays

In [93]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  1,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 1 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [95]:
for row in A:
  print(row[0])

0
5
10
15


In [97]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
1
8
9
10
11
12
13
14
15
16
17
18
19


In [98]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  1,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [100]:
A.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  1],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [101]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  1,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [102]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  1, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Logic Masks

In [103]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [106]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [107]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [108]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [109]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [110]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [111]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])